version: '3.4'
services:
  # back-end api built with golang
  golang-prod:
    restart: always
    build:
      context: golang
      dockerfile: server.Dockerfile
      target: prod
    ports:
      - "5001:5001"
    env_file: .env

  # front-end built with react
  react-prod:
    restart: always
    build:
      context: react
      target: prod
    ports:
      - "3000:3000"

  # nginx is used for ssl termination
  nginx-prod:
    restart: always
    build:
      context: nginx
      target: prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - golang-prod
      - react-prod
