// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	DeleteVideo(ctx context.Context, id int64) (Video, error)
	FindVideoByID(ctx context.Context, id int64) (Video, error)
	GetVideos(ctx context.Context) ([]Video, error)
}

var _ Querier = (*Queries)(nil)
