/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as VideosIndexImport } from './routes/videos/index'
import { Route as VideosUploadImport } from './routes/videos/upload'
import { Route as VideosVideoIdImport } from './routes/videos/$videoId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VideosIndexRoute = VideosIndexImport.update({
  path: '/videos/',
  getParentRoute: () => rootRoute,
} as any)

const VideosUploadRoute = VideosUploadImport.update({
  path: '/videos/upload',
  getParentRoute: () => rootRoute,
} as any)

const VideosVideoIdRoute = VideosVideoIdImport.update({
  path: '/videos/$videoId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/videos/$videoId': {
      id: '/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/videos/$videoId'
      preLoaderRoute: typeof VideosVideoIdImport
      parentRoute: typeof rootRoute
    }
    '/videos/upload': {
      id: '/videos/upload'
      path: '/videos/upload'
      fullPath: '/videos/upload'
      preLoaderRoute: typeof VideosUploadImport
      parentRoute: typeof rootRoute
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  VideosVideoIdRoute,
  VideosUploadRoute,
  VideosIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/videos/$videoId",
        "/videos/upload",
        "/videos/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/videos/$videoId": {
      "filePath": "videos/$videoId.tsx"
    },
    "/videos/upload": {
      "filePath": "videos/upload.tsx"
    },
    "/videos/": {
      "filePath": "videos/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
